# Generated by Django 5.2.6 on 2025-09-12 12:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticationApp', '0001_initial'),
        ('doctorApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits.', regex='^\\d{10}$')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=155)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticationApp.clinicdoctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='PatientVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Pending', 'Pending')], default='Upcoming', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('completed_at', models.CharField(blank=True, choices=[('Government Hospital', 'Government Hospital'), ('Other Private Hospital', 'Other Private Hospital'), ('Admin Doctor', 'Admin Doctor')], max_length=50, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='patientApp.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccine_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorApp.vaccineschedule')),
            ],
            options={
                'verbose_name_plural': 'Patient Vaccine',
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user', 'child_name', 'date_of_birth'], name='patientApp__user_id_366d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['mobile_number', 'gender'], name='patientApp__mobile__41c206_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active', 'created_at'], name='patientApp__is_acti_19fa55_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvaccine',
            index=models.Index(fields=['user', 'patient'], name='patientApp__user_id_38e6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvaccine',
            index=models.Index(fields=['vaccine_schedule', 'status'], name='patientApp__vaccine_068f38_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvaccine',
            index=models.Index(fields=['is_completed', 'completed_on'], name='patientApp__is_comp_a5d7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvaccine',
            index=models.Index(fields=['completed_at', 'due_date', 'created_at'], name='patientApp__complet_fef02c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientvaccine',
            unique_together={('patient', 'vaccine_schedule')},
        ),
    ]
