# Generated by Django 5.2.6 on 2025-09-17 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0002_vaccineschedule_patient'),
        ('patientApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patientvaccine',
            name='patientApp__is_comp_a5d7d4_idx',
        ),
        migrations.AddField(
            model_name='patientvaccine',
            name='custom_vaccine',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patientvaccine',
            name='vaccine_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorApp.vaccineschedule'),
        ),
        migrations.AddIndex(
            model_name='patientvaccine',
            index=models.Index(fields=['is_completed', 'completed_on', 'custom_vaccine'], name='patientApp__is_comp_06d829_idx'),
        ),
    ]
