# Generated by Django 5.2.6 on 2025-12-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0002_remove_patientvaccine_patientapp__is_comp_a5d7d4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvaccine',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientvaccine',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
