# Generated by Django 5.2.6 on 2025-10-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('Per Message', 'Per Message'), ('Monthly Subscription', 'Monthly Subscription'), ('Per Message + Monthly Subscription', 'Per Message + Monthly Subscription')], max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_subscription_fees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='per_message_charges',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
