# Generated by Django 5.2.6 on 2025-10-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0002_user_billing_method_user_monthly_subscription_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, default='dDAd6XyCTyO4nCHxCXjMg1:APA91bFjRTx30KfuaWcXbi0voEtwwb2jVzcXttr_QsgMR64cx7LKzxqI2xZVOXyM3UCus4145-1n-TErc-p9qZmF6Uzhn5AvTaKgi_GbSNMzWMuNpb83WWU', null=True),
        ),
    ]
