# Generated by Django 5.2.6 on 2025-09-12 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, choices=[('doctor', 'Individual Doctor'), ('clinic', 'Clinic / Hospital')], max_length=20, null=True)),
                ('age', models.CharField(choices=[('Birth', 'Birth'), ('6 Weeks', '6 Weeks'), ('10 Weeks', '10 Weeks'), ('14 Weeks', '14 Weeks'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('9 Months', '9 Months'), ('12 Months', '12 Months'), ('15 Months', '15 Months'), ('16–18 Months', '16–18 Months'), ('18 Months', '18 Months'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('4–6 Years', '4–6 Years'), ('5 Years', '5 Years'), ('6 Years', '6 Years'), ('7 Years', '7 Years'), ('8 Years', '8 Years'), ('10 Years', '10 Years'), ('16–18 Years', '16–18 Years')], max_length=20)),
                ('vaccine', models.CharField(max_length=150)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
