# Generated by Django 5.2.6 on 2025-09-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0001_initial'),
        ('patientApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineschedule',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_vaccine_schedules', to='patientApp.patient'),
        ),
    ]
