# Generated by Django 5.2.6 on 2025-09-22 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
        ('doctorApp', '0002_vaccineschedule_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='doctor',
        ),
        migrations.AddField(
            model_name='vaccineschedule',
            name='clinic_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_schedules', to='authenticationApp.clinicdoctor'),
        ),
    ]
