# Generated by Django 5.2.6 on 2025-09-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0006_vaccineschedule_due_date_alter_vaccineschedule_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineschedule',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
