# Generated by Django 5.2.6 on 2025-09-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0008_alter_vaccineschedule_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='vaccineschedule',
            name='age',
            field=models.CharField(choices=[('Birth', 'Birth'), ('6 Weeks', '6 Weeks'), ('10 Weeks', '10 Weeks'), ('14 Weeks', '14 Weeks'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('9 Months', '9 Months'), ('12 Months', '12 Months'), ('15 Months', '15 Months'), ('16–18 Months', '16–18 Months'), ('18 Months', '18 Months'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('4–6 Years', '4–6 Years'), ('5 Years', '5 Years'), ('6 Years', '6 Years'), ('7 Years', '7 Years'), ('8 Years', '8 Years'), ('10 Years', '10 Years'), ('16–18 Years', '16–18 Years')], max_length=20),
        ),
    ]
