# Generated by Django 5.2.6 on 2025-09-30 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0009_remove_vaccineschedule_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineschedule',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccineschedule',
            name='age',
            field=models.CharField(blank=True, choices=[('Birth', 'Birth'), ('6 Weeks', '6 Weeks'), ('10 Weeks', '10 Weeks'), ('14 Weeks', '14 Weeks'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('9 Months', '9 Months'), ('12 Months', '12 Months'), ('15 Months', '15 Months'), ('16–18 Months', '16–18 Months'), ('18 Months', '18 Months'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('4–6 Years', '4–6 Years'), ('5 Years', '5 Years'), ('6 Years', '6 Years'), ('7 Years', '7 Years'), ('8 Years', '8 Years'), ('10 Years', '10 Years'), ('16–18 Years', '16–18 Years')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='VaccineReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
