# Generated by Django 5.2.6 on 2025-09-30 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0010_vaccineschedule_due_date_alter_vaccineschedule_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(default='vaccination', max_length=50)),
                ('recipient', models.CharField(max_length=20)),
                ('child_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vaccine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='VaccineReminderLog',
        ),
    ]
