# Generated by Django 5.2.6 on 2025-10-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0011_reminderlog_delete_vaccinereminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderlog',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
