# Generated by Django 5.2.6 on 2025-10-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0012_reminderlog_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderlog',
            name='child_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
