# Generated by Django 5.2.6 on 2025-10-11 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0013_alter_reminderlog_child_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Firebase Notification Log',
                'verbose_name_plural': 'Firebase Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
