# Generated by Django 5.2.6 on 2025-10-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0014_firebasenotificationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirebaseNotificationLog',
        ),
    ]
