# Generated by Django 5.2.6 on 2025-11-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0016_firebasenotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineschedule',
            name='age_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
