# Generated by Django 5.2.6 on 2025-12-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0017_vaccineschedule_age_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasenotificationlog',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
