# Generated by Django 5.2.6 on 2025-10-10 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pending_previous_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pending_this_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_unpaid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_doctors', models.PositiveIntegerField(blank=True, null=True)),
                ('active_patients', models.PositiveIntegerField(blank=True, null=True)),
                ('total_message_sent', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Analytics',
                'indexes': [models.Index(fields=['total_revenue', 'pending_previous_month'], name='dashboardAp_total_r_071b67_idx'), models.Index(fields=['pending_this_month', 'user_paid'], name='dashboardAp_pending_6991c8_idx'), models.Index(fields=['user_unpaid', 'total_doctors'], name='dashboardAp_user_un_c1a493_idx'), models.Index(fields=['active_patients', 'total_message_sent'], name='dashboardAp_active__f8775e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_method', models.CharField(blank=True, choices=[('Per Message', 'Per Message'), ('Monthly Subscription', 'Monthly Subscription'), ('Per Message + Monthly Subscription', 'Per Message + Monthly Subscription')], max_length=155, null=True)),
                ('total_message_sent', models.PositiveIntegerField()),
                ('billing_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_dues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bill_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(blank=True, choices=[('In Process', 'In Process'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Paid', 'Paid')], default='Pending', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing Management',
                'indexes': [models.Index(fields=['user', 'billing_method'], name='dashboardAp_user_id_b21217_idx'), models.Index(fields=['total_message_sent', 'billing_subtotal', 'gst_collected'], name='dashboardAp_total_m_fec316_idx'), models.Index(fields=['previous_dues', 'total_bill_with_gst'], name='dashboardAp_previou_dde282_idx'), models.Index(fields=['payment_status'], name='dashboardAp_payment_31d1ec_idx')],
            },
        ),
    ]
